#!/usr/bin/env bash
#configures an Nginx server to listen on port 80.
rm /etc/nginx/sites-enabled/default
#this is
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart nginx
service nginx restart

